-- phpMyAdmin SQL Dump
-- version 4.5.4.1deb2ubuntu2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Tempo de geração: 23/04/2018 às 02:35
-- Versão do servidor: 5.7.20-0ubuntu0.16.04.1
-- Versão do PHP: 7.0.22-0ubuntu0.16.04.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Banco de dados: `portal_cinema_1`
--

-- --------------------------------------------------------

--
-- Estrutura para tabela `filmes`
--

CREATE TABLE `filmes` (
  `id` int(11) NOT NULL,
  `nome` varchar(100) DEFAULT NULL,
  `nomeOriginal` varchar(100) DEFAULT NULL,
  `estreia` varchar(50) DEFAULT NULL,
  `duracao` int(11) DEFAULT NULL,
  `genero` varchar(20) DEFAULT NULL,
  `paisOrigem` varchar(50) DEFAULT NULL,
  `diretor` varchar(100) DEFAULT NULL,
  `elenco` text,
  `sinopse` text NOT NULL,
  `poster` varchar(100) NOT NULL,
  `emCartaz` varchar(3) NOT NULL DEFAULT 'off',
  `imgFundo` varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Fazendo dump de dados para tabela `filmes`
--

INSERT INTO `filmes` (`id`, `nome`, `nomeOriginal`, `estreia`, `duracao`, `genero`, `paisOrigem`, `diretor`, `elenco`, `sinopse`, `poster`, `emCartaz`, `imgFundo`) VALUES
(9, 'Vingadores: Guerra Infinita', 'Avengers: Infinity War', '26 de Abril de 2018', 156, 'Aventura', 'Estados Unidos da AmÃ©rica', 'Anthony Russo e Joe Russo', '<p>Chris Evans, Robert Downey Jr., Scarlett Johansson, Chris Hemsworth, Benedict Cumberbatch, Bradley Cooper, Brie Larson</p>\r\n', '<p>O maior e mais mortal confronto de todos os tempos. Os Vingadores e seus aliados Super Her&oacute;is devem se dispor a sacrificar tudo em uma tentativa de derrotar o poderoso Thanos antes que seu ataque de devasta&ccedil;&atilde;o e ru&iacute;na d&ecirc; um fim ao universo.</p>\r\n', 'vingadores_guerra_infinita.jpg', 'nao', 'vingadores_guerra_infinita_bio.jpg'),
(10, 'Jogador NÂº1', 'Ready Player One', '29 de MarÃ§o de 2018', 140, 'Aventura', 'Estados Unidos da AmÃ©rica', 'Steven Spielberg', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-519140/">Tye Sheridan</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-586280/">Olivia Cooke</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-44069/">Ben Mendelsohn</a></p>\r\n', '<p>Num futuro dist&oacute;pico, em 2044, Wade Watts (Tye Sheridan), como o resto da humanidade, prefere a realidade virtual do jogo OASIS ao mundo real. Quando o criador do jogo, o exc&ecirc;ntrico James Halliday (Mark Rylance) morre, os jogadores devem descobrir a chave de um quebra-cabe&ccedil;a diab&oacute;lico para conquistar sua fortuna inestim&aacute;vel. Para vencer, por&eacute;m, Watts ter&aacute; de abandonar a exist&ecirc;ncia virtual e ceder a uma vida de amor e realidade da qual sempre tentou fugir.</p>\r\n', 'jogador_n1.jpg', 'sim', 'jogador_n1_bio.jpg'),
(11, 'Um Lugar Silencioso', 'A Quiet Place', '5 de abril de 2018', 130, 'Suspense', 'Estados Unidos da AmÃ©rica', 'John Krasinski', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-125110/">John Krasinski</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-123054/">Emily Blunt</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-773529/">Millicent Simmonds</a></p>\r\n', '<p>Em uma fazenda dos Estados Unidos, uma fam&iacute;lia do meio-oeste &eacute; perseguida por uma entidade fantasmag&oacute;rica assustadora. Para se protegerem, eles devem permanecer em sil&ecirc;ncio absoluto, a qualquer custo, pois o perigo &eacute; ativado pela percep&ccedil;&atilde;o do som.</p>\r\n', 'lugar_silencioso.jpg', 'sim', NULL),
(12, 'Deadpool 2', 'Deadpool 2', '17 de maio de 2018', 120, 'AÃ§Ã£o', 'Estados Unidos da AmÃ©rica', 'David Leitch', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-74084/">Ryan Reynolds</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-3146/">Josh Brolin</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-104434/">Morena Baccarin</a></p>\r\n', '<p>Sequ&ecirc;ncia das aventuras do Mercen&aacute;rio Tagarela, interpretado por Ryan Reynolds. Na hist&oacute;ria original, o her&oacute;i adquire superpoderes ap&oacute;s uma experi&ecirc;ncia cient&iacute;fica, e decide se vingar da pessoa respons&aacute;vel por sequestrar sua namorada.</p>\r\n', 'deadpool2.jpg', 'nao', NULL),
(13, 'Han Solo: Uma HistÃ³ria Star Wars', 'Solo: A Star Wars Story', '24 de maio de 2018', 120, 'Aventura', 'Estados Unidos da AmÃ©rica', 'Ron Howard', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-136292/">Alden Ehrenreich</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-457862/">Emilia Clarke</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-209532/">Donald Glover</a></p>\r\n', '<p>As aventuras do emblem&aacute;tico mercen&aacute;rio Han Solo (Alden Ehrenreich) e seu fiel escudeiro Chewbacca (Joonas Suotamo) antes dos eventos retratados em <em>Star Wars: Uma Nova Esperan&ccedil;a,&nbsp;</em>inclusive&nbsp;encontrando com Lando Calrissian (Donald Glover).</p>\r\n', 'han_solo.jpg', 'nao', 'han_solo_bio.jpg'),
(14, 'Gnomeu e Julieta: O MistÃ©rio do Jardim', 'Sherlock Gnomes', '31 de maio de 2018', 126, 'AnimaÃ§Ã£o', 'Estados Unidos da AmÃ©rica', 'John Stevenson', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-12839/">Johnny Depp</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-85120/">James McAvoy</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-123054/">Emily Blunt</a></p>\r\n', '<p>Gnomeu e Julieta chegam &agrave; Inglaterra, preocupados em preparar o jardim para a primavera e rever os amigos brit&acirc;nicos. No entanto, a dupla come&ccedil;a a perceber que os gnomos est&atilde;o sendo sequestrados em toda a cidade. Eles recorrem ao g&ecirc;nio da investiga&ccedil;&atilde;o Sherlock Gnomes que, junto de seu fiel companheiro Watson, embarca numa aventura para solucionar o mist&eacute;rio. Sequ&ecirc;ncia da anima&ccedil;&atilde;o Gnomeu e Julieta (2011).</p>\r\n', 'gnomeu.jpg', 'nao', NULL),
(15, 'Oito Mulheres e um Segredo', 'Oceans 8', '7 de junho de 2018', 120, 'ComÃ©dia', 'Estados Unidos da AmÃ©rica', 'Gary Ross', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-4700/">Sandra Bullock</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-28561/">Cate Blanchett</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-421334/">Rihanna</a></p>\r\n', '<p>Rec&eacute;m-sa&iacute;da da pris&atilde;o, Debbie Ocean (Sandra Bullock) planeja executar o assalto do s&eacute;culo em pleno Met Gala, em Nova York, com o apoio de Lou (Cate Blanchett), Nine Ball (Rihanna), Amita (Mindy Kaling), Constance (Awkwafina), Rose (Helena Bonham Carter), Daphne Kluger (Anne Hathaway) e Tammy (Sarah Paulson).</p>\r\n', 'ocean8.jpg', 'nao', NULL),
(16, 'Talvez uma HistÃ³ria de Amor', 'Talvez uma HistÃ³ria de Amor', ' 14 de junho de 2018', 120, 'Nacional', 'Brasil', 'Rodrigo Bernardo', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-471425/">Mateus Solano</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-669245/">Thaila Ayala</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-509518/">Bianca Comparato</a></p>\r\n', '<p>Quando chega em casa, depois de mais um dia corriqueiro no trabalho, Virg&iacute;lio (Mateus Solano) liga a secret&aacute;ria eletr&ocirc;nica e ouve um recado perturbador. &Eacute; uma mensagem de Clara (Thaila Ayala), comunicando o t&eacute;rmino do relacionamento dos dois. Virg&iacute;lio, contudo, n&atilde;o faz a menor ideia de quem &eacute; Clara.&nbsp; Perturbado devido ao seu jeito met&oacute;dico e controlador, ele n&atilde;o se lembra de ter se relacionado com ningu&eacute;m, mas todos ao seu redor pareciam saber do relacionamento dos dois, perguntando como ele est&aacute; se sentindo com o t&eacute;rmino. Agora, ele precisa encontrar essa mulher misteriosa.</p>\r\n', 'talvez_uma_historia.jpg', 'nao', NULL),
(17, 'Legalize JÃ¡!', 'Legalize JÃ¡!', '14 de junho de 2018', 130, 'Nacional', 'Brasil', ' Johnny AraÃºjo, Gustavo BonafÃ© ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-738077/">Renato G&oacute;es</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-646763/">&Iacute;caro Silva</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-21437/">Ernesto Alterio</a></p>\r\n', '<p>Skunk (&Iacute;caro Silva) &eacute; um jovem m&uacute;sico, revoltado com a opress&atilde;o e o preconceito di&aacute;rios sofrido pelas comunidades de baixa renda, que busca expor sua insatisfa&ccedil;&atilde;o atrav&eacute;s da m&uacute;sica. Um dia, ao fugir da pol&iacute;cia, ele literalmente esbarra em Marcelo (Renato G&oacute;es), um vendedor de camisas de bandas de heavy metal. O gosto pelo mesmo estilo musical os aproxima, assim como a habilidade de Marcelo em compor letras de forte cunho social e questionador. Impulsionado por Skunk, ele adentra o universo da m&uacute;sica e, juntos, formam a banda Planet Hemp.</p>\r\n', 'legalize.jpg', 'nao', NULL),
(18, 'Jurassic World: Reino AmeaÃ§ado', 'Jurassic World: Fallen Kingdom', '21 de junho de 2018', 120, 'Aventura', 'Estados Unidos da AmÃ©rica', 'Juan Antonio Bayona', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-98332/">Chris Pratt</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-91615/">Bryce Dallas Howard</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-17412/">B.D. Wong</a></p>\r\n', '<p>Quatro anos ap&oacute;s o fechamento do Jurassic Park, um vulc&atilde;o prestes a entrar em erup&ccedil;&atilde;o p&otilde;e em risco a vida na ilha Nublar. No local n&atilde;o h&aacute; mais qualquer presen&ccedil;a humana, com os dinossauros vivendo livremente. Diante da situa&ccedil;&atilde;o, &eacute; preciso tomar uma decis&atilde;o: deve-se retornar &agrave; ilha para salvar os animais ou abandon&aacute;-los para uma nova extin&ccedil;&atilde;o? Decidida a resgat&aacute;-los, Claire (Bryce Dallas Howard) convoca Owen (Chris Pratt) a retornar &agrave; ilha com ela.</p>\r\n', 'jurassicworld2.jpg', 'nao', 'jurassicworld2_bio.jpg'),
(19, 'Rampage: DestruiÃ§Ã£o Total', 'Rampage', '12 de abril de 2018', 107, 'Aventura', 'EUA', 'Brad Peyton', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-38755/">Dwayne Johnson</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-92692/">Naomie Harris</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-97430/">Malin &Aring;kerman</a></p>\r\n', '<p>Davis Okoye&nbsp; &eacute; um primatologista (Dwayne Johnson), um homem recluso que compartilha um v&iacute;nculo inabal&aacute;vel com George, um gorila muito inteligente que est&aacute; sob seus cuidados desde o nascimento. Quando um experimento gen&eacute;tico desonesto &eacute; feito em um grupo de predadores que inclui o primata, os animais se transformam em monstros que destroem tudo em seu caminho. Agora Okoye tenta conseguir um ant&iacute;doto e impedir que seu amigo provoque uma cat&aacute;strofe global.</p>\r\n', 'rampage.jpg', 'sim', NULL),
(20, 'Antes Que Eu Me EsqueÃ§a', 'Antes Que Eu Me EsqueÃ§a', '24 de maio de 2018', 100, 'ComÃ©dia', 'Brasil', 'Tiago Arakilian', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-19489/">Jos&eacute; de Abreu</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-594483/">Danton Mello</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-203815/">Guta Stresser</a></p>\r\n', '<p>Aos 80 anos de idade, Polidoro (Jos&eacute; de Abreu) &eacute; um soberbo juiz aposentado que vive sozinho e mal tem contato com o filho Paulo (Danton Mello), pianista fracassado. Quando sua filha mais pr&oacute;xima, Bia (Let&iacute;cia Isnard), entra com uma a&ccedil;&atilde;o para interdit&aacute;-lo, ele decide investir seus fundos numa boate de striptease em Copacabana.</p>\r\n', 'antes_que_eu_me_esqueca.jpg', 'nao', NULL),
(21, 'Pedro Coelho', 'Peter Rabbit', '22 de marÃ§o de 2018', 90, 'AnimaÃ§Ã£o', 'EUA, Reino Unido, AustrÃ¡lia', 'Will Gluck', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-398314/">Domhnall Gleeson</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-64704/">Rose Byrne</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-973/">Sam Neill</a></p>\r\n', '<p>Pedro Coelho &eacute; um animal rebelde que apronta todas no quintal e at&eacute; dentro da casa do&nbsp;Mr. McGregor (Domhnall Gleeson), com quem trava uma dura batalha pelo carinho da amante de animais Bea (Rose Byrne).</p>\r\n', 'pedro_coelho.jpg', 'sim', NULL),
(22, 'Tomb Raider - A Origem', 'Tomb Raider', '15 de marÃ§o de 2018', 158, 'Aventura', 'Estados Unidos', 'Roar Uthaug', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-515413/">Alicia Vikander</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-33032/">Dominic West</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-53292/">Walton Goggins</a></p>\r\n\r\n<p>&nbsp;</p>\r\n', '<p>Aos 21 anos, Lara Croft (Alicia Vikander) leva a vida fazendo entregas de bicicleta pelas ruas de Londres, se recusando a assumir a companhia global do seu pai desaparecido (Dominic West) h&aacute; sete anos, ideia que ela se recusa a aceitar. Tentando desvendar o sumi&ccedil;o do pai, ela decide largar tudo para ir at&eacute; o &uacute;ltimo lugar onde ele esteve e inicia uma perigosa aventura numa ilha japonesa.</p>', 'tomb_raider_2018.jpg', 'sim', 'tomb_raider_2018_bio.jpg'),
(23, 'Pantera Negra', ' Black Panther', '15 de Fevereiro de 2018', 215, 'AÃ§Ã£o', 'Estados Unidos', ' Ryan Coogler ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-133640/">Chadwick Boseman</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-120365/">Michael B. Jordan</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-582633/">Lupita Nyong&#39;o</a> <a href="http://www.adorocinema.com/filmes/filme-130336/creditos/"> </a></p>\r\n', '<p>&nbsp;Ap&oacute;s a morte do rei T&#39;Chaka (John Kani), o pr&iacute;ncipe T&#39;Challa (Chadwick Boseman) retorna a Wakanda para a cerim&ocirc;nia de coroa&ccedil;&atilde;o. Nela s&atilde;o reunidas as cinco tribos que comp&otilde;em o reino, sendo que uma delas, os Jabari, n&atilde;o apoia o atual governo. T&#39;Challa logo recebe o apoio de Okoye (Danai Gurira), a chefe da guarda de Wakanda, da irm&atilde; Shuri (Letitia Wright), que coordena a &aacute;rea tecnol&oacute;gica do reino, e tamb&eacute;m de Nakia (Lupita Nyong&#39;o), a grande paix&atilde;o do atual Pantera Negra, que n&atilde;o quer se tornar rainha. Juntos, eles est&atilde;o &agrave; procura de Ulysses Klaue (Andy Serkis), que roubou de Wakanda um punhado de vibranium, alguns anos atr&aacute;s.</p>\r\n', 'pantera_negra.jpg', 'off', NULL),
(24, 'Covil de LadrÃµes', ' Den Of Thieves', ' 5 de abril de 2018', 220, 'Suspense', 'Estados Unidos', ' Christian Gudegast ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-21087/">Gerard Butler</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-169981/">Pablo Schreiber</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-99417/">Curtis &#39;50 Cent&#39; Jackson</a> <a href="http://www.adorocinema.com/filmes/filme-228972/creditos/"> </a></p>\r\n', '<p>Em Los Angeles, capital dos roubos a banco, um banho de sangue coloca em interse&ccedil;&atilde;o a vida de dois grupos: a radical unidade de elite do departamento de pol&iacute;cia local, liderada pelo desmedido Nick (Gerard Butler), e a equipe de assaltantes de banco mais arrojada em atividade. Enquanto os criminosos planejam um ataque ambicioso at&eacute; ent&atilde;o tido como imposs&iacute;vel, os homens da lei apertam o cerco pelo elo aparentemente mais fraco da gangue.</p>\r\n', 'covil_de_ladroes.jpg', 'sim', NULL),
(25, 'Madame', 'Madame', ' 29 de marÃ§o de 2018', 130, 'Drama', 'FranÃ§a', ' Amanda Sthers ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-17446/">Toni Collette</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-10/">Harvey Keitel</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-10618/">Rossy de Palma</a></p>\r\n', '<p>Rec&eacute;m-chegados em Paris, os americanos Anne (Toni Collette) e Bob (Harvey Keitel) organizam um luxuoso jantar para 12 pessoas. Quando uma presen&ccedil;a inesperada faz o n&uacute;mero virar 13, a supersticiosa anfitri&atilde; se recusa a dar chance ao azar e transforma a empregada Maria (Rossy de Palma) em convidada especial espanhola. Inicialmente receosa, ela acaba conquistando um comerciante de arte brit&acirc;nico com seu jeito &uacute;nico e o relacionamento se aprofunda para al&eacute;m da noite de festa, para desespero dos controladores patr&otilde;es de Maria.</p>\r\n', 'madame.jpg', 'sim', NULL),
(26, 'MegatubarÃ£o', 'The Meg', ' 9 de agosto de 2018', 120, 'Suspense', 'Estados Unidos', ' Jon Turteltaub ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-28586/">Jason Statham</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-90905/">Bingbing Li</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-50619/">Rainn Wilson</a></p>\r\n', '<p>Na fossa mais profunda do Oceano Pac&iacute;fico, a tripula&ccedil;&atilde;o de um submarino fica presa dentro do local ap&oacute;s ser atacada por uma criatura pr&eacute;-hist&oacute;rica que se achava estar extinta, um tubar&atilde;o de mais de 20 metros de comprimento, o Megalodon. Para salv&aacute;-los, ocean&oacute;grafo chin&ecirc;s (Winston Chao) contrata Jonas Taylor (Jason Statham), um mergulhador especializado em resgates em &aacute;gua profundas que j&aacute; encontrou com a criatura anteriormente.</p>\r\n', 'megatubarao.jpg', 'nao', NULL),
(27, 'Os IncrÃ­veis 2', ' The Incredibles 2', '28 de junho de 2018', 120, 'AnimaÃ§Ã£o', 'Estados Unidos', ' Brad Bird ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-58347/">Craig T. Nelson</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-4202/">Holly Hunter</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-14454/">Samuel L. Jackson</a></p>\r\n', '<p>Quando Helena P&ecirc;ra &eacute; chamada para voltar a lutar contra o crime como a super-hero&iacute;na Mulher-El&aacute;stica, cabe ao seu marido, Roberto, a tarefa de cuidar das crian&ccedil;as, especialmente o beb&ecirc; Zez&eacute;. O que ele n&atilde;o esperava era que o ca&ccedil;ula da fam&iacute;lia tamb&eacute;m tivesse superpoderes, que surgem sem qualquer controle.</p>\r\n', 'os_incriveis_2.jpg', 'nao', NULL),
(28, 'SubmersÃ£o', 'Submergence', '19 de abril de 2018', 152, 'Suspense', 'Estados Unidos', ' Wim Wenders ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-85120/">James McAvoy</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-515413/">Alicia Vikander</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-46104/">Alexander Siddig</a></p>\r\n', '<p>Danielle (Alicia Vikander) &eacute; uma exploradora do oceano que descobre um novo desafio: uma terr&iacute;vel, por&eacute;m pioneira, descida ao abismo &Aacute;rtico. James (James McAvoy) &eacute; um empreiteiro acusado de ser um espi&atilde;o e interrogado por jihadistas africanos que ir&aacute; se unir &agrave; mo&ccedil;a para ajud&aacute;-la em sua miss&atilde;o.</p>\r\n', 'submersao.jpg', 'nao', NULL),
(29, 'Desejo de Matar', ' Death Wish', ' 10 de maio de 2018', 109, 'AÃ§Ã£o', 'Estados Unidos', ' Eli Roth ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-6693/">Bruce Willis</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-4152/">Elisabeth Shue</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-788862/">Camila Morrone</a></p>\r\n', '<p>Um homem gentil tem sua vida transformada quando sua fam&iacute;lia &eacute; abalada por um ato de viol&ecirc;ncia que machuca a todos. Em busca de justi&ccedil;a, ele se transforma em uma m&aacute;quina mort&iacute;fera, para conseguir fazer justi&ccedil;a com as pr&oacute;prias m&atilde;os.</p>\r\n', 'desejo_de_matar.jpg', 'nao', NULL),
(30, 'Mamma Mia 2', 'Mamma Mia: Here We Go Again!', ' 2 de agosto de 2018', 120, 'ComÃ©dia', 'Estados Unidos', ' Ol Parker ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-101918/">Amanda Seyfried</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-9/">Meryl Streep</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-505959/">Lily James</a></p>\r\n', '<p>Ao descobrir que est&aacute; gr&aacute;vida, Sophie (Amanda Seyfried) busca inspira&ccedil;&atilde;o para a maternidade lembrando do passado da m&atilde;e. Nos anos 70 a jovem Donna (Lily James) viveu muitas aventuras com seu grupo musical &quot;Donna &amp; The Dynamo&quot;, parceria com as amigas Tanya (Jessica Keenan Wynn) e Rosie (Alexa Davies). Por&eacute;m, mais do que isso, ela se apaixonou e viveu relacionamentos intensos com tr&ecirc;s homens bem diferentes: Harry (Hugh Skinner), Sam (Jeremy Irvine) e Bill (Josh Dylan).&nbsp;<br />\r\n&nbsp;</p>\r\n', 'mama_mia_2.jpg', 'nao', NULL),
(31, 'A Noite do Jogo', ' Game Night', ' 10 de maio de 2018', 99, 'ComÃ©dia', 'Estados Unidos', ' Jonathan Goldstein (XII), John Francis Daley ', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-59046/">Jason Bateman</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-81263/">Rachel McAdams</a>, <a href="http://www.adorocinema.com/personalidades/personalidade-97817/">Kyle Chandler</a></p>\r\n', '<h2>Max (Jason Bateman) e Annie (Rachel McAdams) participam de um grupo de casais que organizam noites de jogos. Quando o irm&atilde;o de de Max, Brooks (Chandler), chega, ele decide organizar uma festa de assassinato e mist&eacute;rio. Quando Brooks &eacute; sequestrado, eles acreditam que tudo faz parte da misteriosa brincadeira. Os seis amigos competitivos precisam resolver o caso para vencer o jogo, cujo rumo vai se tornando cada vez mais inesperado.</h2>\r\n', 'a_noite_do_jogo.jpg', 'nao', NULL),
(32, 'A Livraria', 'The Bookshop', ' 22 de marÃ§o de 2018', 113, 'Drama', 'Espanha', ' Isabel Coixet', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-35010/">Emily Mortimer</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-6351/">Bill Nighy</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-10461/">Patricia Clarkson</a></p>\r\n', '<p>No final da d&eacute;cada de 50, uma mulher (Emily Mortimer) rec&eacute;m-chegada em uma pacata cidade do litoral da Inglaterra decide abrir uma livraria. Contudo, sua iniciativa &eacute; vista com maus olhos pela conservadora comunidade local, que passa a se opor tanto a ela quanto ao seu neg&oacute;cio, obrigando-a lutar por seu estabelecimento.</p>\r\n', 'a_livraria.jpg', 'sim', NULL),
(33, 'A OdissÃ©ia', ' L\'Odyssee', ' 22 de marÃ§o de 2018', 123, 'Drama', 'FranÃ§a', ' JÃ©rÃ´me Salle', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-1004/">Lambert Wilson</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-228780/">Pierre Niney</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-24411/">Audrey Tautou</a></p>\r\n', '<p>O aventureiro oce&acirc;nico e cineasta franc&ecirc;s&nbsp;Jacques-Yves Cousteau (Lambert Wilson) larga a vida na terra ao embarcar em uma grande viagem no imenso navio Calypso, sua nova casa. Com o passar dos anos, no entanto, seu amor pelo mundo submerso - e principalmente suas possibilidades de neg&oacute;cios - relega a segundo plano a mulher (Audrey Tautou) e os filhos. Ap&oacute;s crescer ressentido num internato, Phillippe (Pierre Niney) volta a bordo apesar da p&eacute;ssima rela&ccedil;&atilde;o com o pai e os dois precisam superar as diferen&ccedil;as e m&aacute;goas para sobreviver em mares gelados.</p>\r\n', 'a_odisseia.jpg', 'sim', NULL),
(34, 'MÃ¡quinas Mortais', ' Mortal Engines', ' 13 de dezembro de 2018', 120, 'Aventura', 'Estados Unidos', ' Christian Rivers', '<p>:&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-20175/">Hugo Weaving</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-594094/">Hera Hilmar</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-247461/">Robert Sheehan</a>&nbsp;</p>\r\n', '<p>Anos depois da &quot;Guerra dos Sessenta Minutos&quot;. A Terra est&aacute; destru&iacute;da e para sobreviver as cidades se movem em rodas gigantes, conhecidas como Cidades Tra&ccedil;&atilde;o, e lutam com outras para conseguir mais recursos naturais. Quando Londres se envolve em um ataque, Tom (Robert Sheehan) &eacute; lan&ccedil;ado para fora da cidade junto com uma fora-da-lei e os dois juntos precisam lutar para sobreviver e ainda enfrentar uma amea&ccedil;a que coloca a vida no planeta em risco.<br />\r\n&nbsp;</p>\r\n', 'maquinas_mortais.jpg', 'nao', NULL),
(35, 'Um Dia para Viver', '24 Hours To Live', '10 de maio de 2018', 93, 'AÃ§Ã£o', 'Estados Unidos', ' Brian Smrz', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-3336/">Ethan Hawke</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-577177/">Paul Anderson (XVIII)</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-1909/">Rutger Hauer</a></p>\r\n', '<p>Um assassino (Ethan Hawke) ganha uma segunda chance quando seu empregador o traz de volta &agrave; vida temporariamente, logo ap&oacute;s ter sido morto no trabalho. Ele tem 24 horas para realizar sua miss&atilde;o e se redimir.</p>\r\n', 'um_dia_para_viver.jpg', 'nao', NULL),
(37, 'No Olho do FuracÃ£o', 'The Hurricane Heist', ' 7 de junho de 2018 ', 100, 'AÃ§Ã£o', 'Estados Unidos', ' Rob Cohen', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-101335/">Toby Kebbell</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-103331/">Maggie Grace</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-92826/">Ryan Kwanten</a>&nbsp;</p>\r\n', '<p>Um grupo de criminosos planeja roubar 600 milh&otilde;es de d&oacute;lares do tesouro americano durante a passagem de um furac&atilde;o. No entanto, seus planos s&atilde;o interrompidos quando o fen&ocirc;meno meteorol&oacute;gico atinge o n&iacute;vel 5, considerado o mais grave de todos, e eles precisam do c&oacute;digo de seguran&ccedil;a que apenas uma funcion&aacute;ria do banco tem conhecimento.&nbsp;</p>\r\n', 'no_olho_do_furacao.jpg', 'nao', NULL),
(38, 'Os Estranhos-CaÃ§ada Noturna', 'The Strangers: Prey at Night', ' 31 de maio de 2018', 85, 'Terror', 'Estados Unidos', ' Johannes Roberts', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-182557/">Bailee Madison</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-105155/">Christina Hendricks</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-76254/">Martin Henderson</a></p>\r\n', '<p>eguindo os acontecimentos do primeiro filme, uma nova fam&iacute;lia receber&aacute; a terr&iacute;vel visita de tr&ecirc;s psicopatas - que t&ecirc;m como &uacute;nico objetivo transformar suas vidas em um inferno na Terra.&nbsp;</p>\r\n', 'os_estranhos_cacada_noturna.jpg', 'nao', NULL),
(39, 'Vidas a Deriva', 'Adrift', ' 19 de julho de 2018', 105, 'AÃ§Ã£o', 'Estados Unidos', ' Baltasar KormÃ¡kur', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-111855/">Shailene Woodley</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-438373/">Sam Claflin</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-72895/">Jeffrey Thomas</a></p>\r\n', '<p>Tami Oldham (Shailene Woodley) e Richard Sharp (Sam Claflin) velejam pelo Taiti quando s&atilde;o atingidos por uma terr&iacute;vel tempestade. Passada a tormenta, ela se v&ecirc; sozinha na embarca&ccedil;&atilde;o em ru&iacute;nas e tenta encontrar uma maneira de salvar a pr&oacute;pria vida e a do parceiro.</p>\r\n', 'vidas_a_deriva.jpg', 'nao', NULL),
(40, 'Attack on Titan: Fim do Mundo', 'Shingeki no kyojin endo obu za wÃ¢rudo', ' 13 de maio de 2018 ', 87, 'AÃ§Ã£o', 'JapÃ£o', ' Shinji Higuchi', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-254079/">Haruma Miura</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-650135/">Hiroki Hasegawa</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-192510/">Kanata Hongo</a></p>\r\n', '<p>Eren J&auml;eger continua lutando na guerra entre os&nbsp;Tit&atilde;s e os humanos sobreviventes. &Agrave; medida que a batalha continua, ele descobre que tem a habilidade de se transformar em um Tit&atilde;. Agora, as pessoas que Eren Jurou proteger, o consideram mais um dos mosntros que precisam derrotar.&nbsp;&nbsp;</p>\r\n', 'attack_on_titan_fim_do_mundo.jpg', 'nao', NULL),
(43, 'Gringo-Vivo ou Morto', 'Gringo', ' 3 de maio de 2018', 110, 'ComÃ©dia', 'Estados Unidos', 'Nash Edgerton', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-8258/">Joel Edgerton</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-12563/">Charlize Theron</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-126702/">David Oyelowo</a></p>\r\n', '<p>Uma mistura de com&eacute;dia e a&ccedil;&atilde;o que explora a luta para sobreviv&ecirc;ncia do empres&aacute;rio Harold Soyinka (David Oyelowo) depois que ele atravessa a limite de cidad&atilde;o respeitador da lei e se transforma em um criminoso procurado.</p>\r\n', 'gringo_vivo_ou_morto.jpg', 'nao', NULL),
(44, 'Lua de JÃºpiter', 'Jupiter holdja', ' 31 de maio de 2018', 123, 'Drama', 'Hungria', ' KornelMundruczo', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-7069/">Merab Ninidze</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-809739/">Zsombor J&eacute;ger</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-2426/">Gy&ouml;rgy Cserhalmi</a></p>\r\n', '<p>Aryan, um jovem migrante, &eacute; baleado enquanto tentava ilegalmente cruzar a fronteira. Depois do choque provocado pelo acidente, acaba descobrindo que agora tem o poder de levitar. Agora preso em um campo refugiados, ele ter&aacute; que contar com a ajuda do Dr. Stern, que tem interesses muito espec&iacute;ficos em sua habilidade sobrenatural.</p>\r\n', 'lua_de_jupiter.jpg', 'nao', NULL),
(45, 'Hunter Killer', 'Hunter Killer', ' 15 de novembro de 2018', 120, 'Suspense', 'Estados Unidos', ' Donovan Marsh', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-21087/">Gerard Butler</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-14092/">Billy Bob Thornton</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-165792/">Common</a></p>\r\n', '<p>Um general rapta o presidente da R&uacute;ssia, que precisa ser resgatado por um capit&atilde;o americano de submarinos e a for&ccedil;a de opera&ccedil;&otilde;es especiais da marinha dos Estados Unidos.</p>\r\n', 'hunter_killer.jpg', 'nao', NULL),
(46, 'Toy Story 4', 'Toy Story 4', ' 20 de junho de 2019', 120, 'AnimaÃ§Ã£o', 'Estados Unidos', ' Josh Cooley', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-14100/">Tom Hanks</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-5198/">Joan Cusack</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-4011/">Laurie Metcalf</a></p>\r\n', '<p>Nova aventura envolvendo o caub&oacute;i Woody, o astronauta Buzz Lightyear e seus amigos brinquedos.</p>\r\n', 'toy_story_4.jpg', 'nao', NULL),
(47, 'Esplendor', 'Hirari', ' 10 de maio de 2018 ', 101, 'Drama', 'JapÃ£o', ' Naomi Kawase', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-11650/">Masatoshi Nagase</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-414744/">Ayame Misaki</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-90995/">Tatsuya Fuji</a></p>\r\n', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-11650/">Masatoshi Nagase</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-414744/">Ayame Misaki</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-90995/">Tatsuya Fuji</a></p>\r\n', 'esplendor.jpg', 'nao', NULL),
(48, 'Teu Mundo NÃ£o Cabe nos meus Olhos', 'Teu Mundo NÃ£o Cabe nos meus Olhos', ' 3 de maio de 2018', 120, 'Nacional', 'Brasil', ' Paulo Nascimento', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-5182/">Edson Celulari</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-51329/">Soledad Villamil</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-568677/">Leonardo Machado</a></p>\r\n', '<p>Vit&oacute;rio (Edson Celulari), cego de nascen&ccedil;a, &eacute; dono de uma pizzaria herdada por seu pai no tradicional bairro do Bixiga, em S&atilde;o Paulo, e &eacute; considerado famoso por oferecer a melhor pizza dos arredores. Vivendo uma vida feliz com a mulher Clarice (Soledad Villamil) e a filha Al&iacute;cia, ele sente que superou todas as dificuldades da cegueira e que deu a volta por cima. Mas, ao descobrir que existe a possibilidade de enxergar, Vit&oacute;rio inicia um conflito consigo mesmo e precisa tomar uma grande decis&atilde;o.</p>\r\n', 'teu_mundo_nao_cabe_nos_meus_olhos.jpg', 'nao', NULL),
(49, 'Robin Hood', 'Robin Hood', ' 22 de novembro de 2018', 120, 'Aventura', 'Estados Unidos', ' Otto Bathurst', '<p>&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-638478/">Taron Egerton</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-466129/">Eve Hewson</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-32404/">Jamie Foxx</a>&nbsp;</p>\r\n', '<p>A origem da famosa lenda sobre o ladr&atilde;o que rouba dos ricos para dar aos pobres. Robin Hood (Taron Egerton) volta das&nbsp;Cruzadas e surpreende-se ao encontrar a Floresta Sherwood infestada de criminosos, no mais completo caos. Ele n&atilde;o deixar&aacute; que as coisas permane&ccedil;am desse jeito.<br />\r\n&nbsp;</p>\r\n', 'robin_hood.jpg', 'nao', NULL),
(50, 'Aos teus olhos', 'Aos teus olhos', '12 de Abril de 2018', 90, 'Drama', 'Brasil', 'Carolina Jabor', '<p><a href="http://www.adorocinema.com/personalidades/personalidade-221612/">Daniel de Oliveira</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-222016/">Malu Galli</a>,&nbsp;<a href="http://www.adorocinema.com/personalidades/personalidade-19500/">Marco Ricca</a></p>\r\n', '<p>Rubens (Daniel de Oliveira) &eacute; um professor de nata&ccedil;&atilde;o carism&aacute;tico e extrovertido, que d&aacute; aulas para pr&eacute;-adolescentes em um clube. Querido por todos devido ao seu jeito brincalh&atilde;o e parceiro, ele se v&ecirc; em apuros quando um de seus alunos, Alex (Lu&iacute;s Felipe Melo), diz &agrave; m&atilde;e que o professor lhe deu um beijo na boca no vesti&aacute;rio. Alegando inoc&ecirc;ncia, Rubens &eacute; acusado pelos pais da crian&ccedil;a e passa a ter que lidar com um verdadeiro linchamento virtual, que tem in&iacute;cio atrav&eacute;s de mensagens de WhatsApp e explode de vez quando chega ao Facebook.</p>\r\n', 'aos_teus_olhos.jpg', 'sim', NULL),
(51, '2001 - Uma OdissÃ©ia no EspaÃ§o', '2001: A Space Odyssey', '29 de Abril de 1968', 150, 'Aventura', 'EUA, Inglaterra', 'Stanley Kubrick', '<p>&nbsp;<a href="http://omelete.com.br/personalidades/keir-dullea/">Keir Dullea</a>&nbsp;,&nbsp;<a href="http://omelete.com.br/personalidades/douglas-rain/">Douglas Rain</a>&nbsp;,&nbsp;<a href="http://omelete.com.br/personalidades/gary-lockwood/">Gary Lockwood</a>&nbsp;,&nbsp;<a href="http://omelete.com.br/personalidades/william-sylvester/">William Sylvester</a>&nbsp;,&nbsp;<a href="http://omelete.com.br/personalidades/daniel-richter/">Daniel Richter</a>&nbsp;,<a href="http://omelete.com.br/personalidades/leonard-rossiter/">Leonard Rossiter</a>&nbsp;,&nbsp;<a href="http://omelete.com.br/personalidades/margaret-tyzack/">Margaret Tyzack</a></p>\r\n', '<p>Uma viagem desde o passado pr&eacute;-hist&oacute;rico dos nossos antepassados, quando um grupo de macacos encontra um misterioso mon&oacute;lito e dele obt&eacute;m conhecimentos que resultam na evolu&ccedil;&atilde;o do Homem, at&eacute; ao espa&ccedil;o colonizado pelos humanos, no ano 2001. A descoberta de um outro mon&oacute;lito na Lua, proveniente de uma regi&atilde;o junto a J&uacute;piter, leva ao lan&ccedil;amento de uma expedi&ccedil;&atilde;o liderada pelo astronauta David Bowman para investigar a origem do objeto extraterrestre. Quando a miss&atilde;o &eacute; colocada em risco por HAL 9000, o supercomputador que controla a nave espacial, Bowman ter&aacute; de vencer a m&aacute;quina antes de viajar at&eacute; ao local de origem do admir&aacute;vel objeto.</p>\r\n', '2001.jpg', 'off', '2001_bio.jpg'),
(52, 'Westworld', 'Westworld', '21 de novembro de 1973', 88, '11', 'Estados Unidos da AmÃ©rica', 'Michael Crichton', 'Richard Benjamin, Yul Brynner, James Brolin, Linda Scott, Alan Oppenheimer, Norman Bartold\n', '<p>Welcome to Westworld, where nothing can go wrong...go wrong...go wrong....Writer/director Michael Crichton has concocted a futuristic &quot;Disneyland for adults&quot;, a remote resort island where, for a hefty fee, one can indulge in one&#39;s wildest fantasies. Businessmen James Brolin and Richard Benjamin are just crazy about the old west, thus they head to the section of Westworld populated by robot desperadoes, robot lawmen, robot dance-hall gals, and the like. Benjamin&#39;s first inkling that something is amiss occurs when, during a mock showdown with robot gunslinger Yul Brynner, Brolin is shot and killed for real.</p>\n', 'westworld.jpg', 'off', 'westworld_fundo.jpg');

--
-- Índices de tabelas apagadas
--

--
-- Índices de tabela `filmes`
--
ALTER TABLE `filmes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de tabelas apagadas
--

--
-- AUTO_INCREMENT de tabela `filmes`
--
ALTER TABLE `filmes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=53;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
