-- MySQL Script generated by MySQL Workbench
-- 03/31/18 22:09:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portal_cinema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portal_cinema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal_cinema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `portal_cinema` ;

-- -----------------------------------------------------
-- Table `portal_cinema`.`filmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cinema`.`filmes` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `nomeOriginal` VARCHAR(100) NOT NULL,
  `estreia` VARCHAR(20) NOT NULL,
  `genero` VARCHAR(20) NOT NULL,
  `direcao` VARCHAR(100) NOT NULL,
  `elenco` TEXT NOT NULL,
  `sinopse` TEXT NOT NULL,
  `duracao` VARCHAR(11) NOT NULL,
  `cartaz` CHAR(3) NULL DEFAULT 'off',
  `breve` CHAR(3) NULL DEFAULT 'off',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portal_cinema`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cinema`.`usuarios` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `portal_cinema`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_cinema`.`noticias` (
  `id` SMALLINT(6) NOT NULL AUTO_INCREMENT,
  `id_usuario` SMALLINT(6) NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `titulo` VARCHAR(100) NOT NULL,
  `subtitulo` VARCHAR(200) NOT NULL,
  `texto` TEXT NULL,
  `img` VARCHAR(100) NULL DEFAULT NULL,
  `imgSlideshow` VARCHAR(100) NULL DEFAULT NULL,
  `destaque` CHAR(3) NULL DEFAULT 'off',
  `tipoNoticia` VARCHAR(20) NULL DEFAULT NULL,
  `filme` SMALLINT(6) NULL,
  `pais` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_ID_usuario` (`id_usuario` ASC),
  INDEX `FK_ID_filme_idx` (`filme` ASC),
  CONSTRAINT `FK_ID_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `portal_cinema`.`usuarios` (`id`),
  CONSTRAINT `FK_ID_filme`
    FOREIGN KEY (`filme`)
    REFERENCES `portal_cinema`.`filmes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
